plugins {
    id 'java'
    id 'org.springframework.boot' version '4.0.6'
    id 'io.spring.dependency-management' version '1.1.7'
}


group = 'me.zonesafe'
version = '0.0.1-SNAPSHOT'
description = 'zonesafe_be'


java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jdbc'
    implementation 'org.springframework.boot:spring-boot-starter-jdbc'
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'

    // JPA 설정 추가
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    // ModelMapper 의존성 추가
    implementation 'org.modelmapper:modelmapper:3.1.1'

    implementation 'com.fasterxml.jackson.core:jackson-databind'
    // 날짜/시간 처리를 위한 Jackson 확장팩 추가!
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'

    // Redis 연동을 위한 라이브러리 추가
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'

    // WebSocket / STOMP
    implementation 'org.springframework.boot:spring-boot-starter-websocket'


    compileOnly 'org.projectlombok:lombok'
    runtimeOnly 'com.mysql:mysql-connector-j'
    annotationProcessor 'org.projectlombok:lombok'
    testImplementation 'org.springframework.boot:spring-boot-starter-data-jdbc-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-jdbc-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    testCompileOnly 'org.projectlombok:lombok'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testAnnotationProcessor 'org.projectlombok:lombok'
}

tasks.named('test') {
    useJUnitPlatform()
}
